### ISSUE TITLE
Non paid vacation

### ISSUE THREAD

**Issue by teghnet** [konradbartecki/Podatki.wtf.issues#1]
I am thinking about comparing salaries with paid vacation days to non-paid vacation days. 

When one does not have the option of paid leave it usually means that the number of days worked in a year is still ~225 so it would be cool to have a switch that will say if the vacation days are paid.

This way you can compare yearly salaries for both scenarios.

Great work BTW.

**Comment by konradbartecki** [comment]
Hey thanks for the feedback!

This feature is actually already here, but maybe discoverability is not to good, I am open to suggestions how to improve that.

If you have no paid vacations then you are de facto paid a hourly rate.
Therefore if you want to compare a paid vacations to non-paid vacations salary you should:

1. Type in yearly or monthly salary
2. In case of non-paid vacations type 0
2. Change the rate type checkbox to PLN/h, it will automatically convert to an hourly rate
3. Now you can type in the amount of your non-paid vacation days.

For monthly and yearly salaries I am assuming that you are going to get that amount every month/year no matter what, so then we are assuming also that vacation days are paid. If you manipulate the vacation days amount then you will see that the actual hourly rate will change.

**Comment by teghnet** [comment]
Oh... I did not think of that... 
Thanks.
