### ISSUE TITLE
Unsupported client detection regarding Microsoft Store link

### ISSUE THREAD

**Issue by ochmanski** [konradbartecki/Podatki.wtf.issues#11]
Hi!
First of all, I really like your tool. Good work 😀

I've noticed that you had added a link to Microsoft store's `Podatki.wtf` app. It's nice and all but I'm using macOS so no Microsoft app for me. My suggestion is that if a client that cannot use MS Store apps, link to MS Store should not be visible

<img width="1792" alt="Screenshot 2021-04-23 at 11 53 45" src="https://user-images.githubusercontent.com/24656679/115854518-99bfd600-a42a-11eb-96c2-5308b783cb11.png">

**Comment by konradbartecki** [comment]
Fixed, please check and close
