### ISSUE TITLE
ZUS rate "Tylko zdrowotny (6mc) / UoP" not loaded on refresh

### ISSUE THREAD

**Issue by szulcmaciej** [konradbartecki/Podatki.wtf.issues#14]
Hi, I found a minor issue with ZUS rate "Tylko zdrowotny (6mc) / UoP".
After refreshing the page, the rate is changed to "Normalna (duży ZUS)". 

When I change the rate from "Normalna (duży ZUS)" to "Tylko zdrowotny", the URL in the browser is changed properly, for example from
```
https://www.podatki.wtf/?n=100&t=1
```
to
```
https://www.podatki.wtf/?n=100&t=1&s=2
```

But when I refresh the page or just hit this second URL, the selected ZUS rate is "Normalna (duży ZUS)". 
Seems like ZUS rate isn't set properly with "&s=2" in the URL when loading the page.
Other ZUS rates are "saved" correctly when refreshing :)

Anyway, great tool, thanks! :)

**Comment by konradbartecki** [comment]
Wow, good catch, thank you so much!
I'll fix that in the next update which is happening soon™️

**Comment by konradbartecki** [comment]
Thanks, if you want to know the backstory, long time ago I didn't have the "start relief/tylko zdrowotny" implemented, so I disabled it from loading via an url.

![image](https://user-images.githubusercontent.com/3373490/149655424-9fdbf8e1-2395-44d3-a4a0-29d438c9ce47.png)

Then one day I implemented this and forgot to re-enable the loading via an URL.
It should work right now, thanks a lot again!
I'm closing this ticket, but please let me know if anything.
