### ISSUE TITLE
Application hangs, when PLN/m is set to 25000

### ISSUE THREAD

**Issue by kudlatykaskader** [konradbartecki/Podatki.wtf.issues#16]
![Screenshot_11](https://user-images.githubusercontent.com/17649388/149909206-cfd1b670-38a7-45cb-9aea-d019449853b0.png)
![Screenshot_12](https://user-images.githubusercontent.com/17649388/149909215-b9f23943-4202-4a13-b9ce-54bcbd89a4bf.png)

**Comment by konradbartecki** [comment]
Thanks! Fixed!

**Comment by kudlatykaskader** [comment]
What was special about that number?

**Comment by konradbartecki** [comment]
for 60k/y <-> 300k/y (which is 25k/mo) a 509,27 PLN NFZ rate is applied
for values >300k/y a 916 PLN NFZ rate should apply.
there was an error when my code tried to apply both NFZ rates at the same time
