### ISSUE TITLE
[Enhancement/bug] Calculation summary in other currencies should be available as well

### ISSUE THREAD

**Issue by rafek1241** [konradbartecki/Podatki.wtf.issues#23]
![image](https://user-images.githubusercontent.com/9272027/157434622-6cbacfb9-2628-402e-8b0f-cd1a824a29cd.png)

When I select a different currency than `PLN`, it should be reflected in the summary. It would be great to have it configurable in options.

**Comment by konradbartecki** [comment]
Thank you, I was thinking about it, but these two currencies should separated as in two pickers.
This is because usually people get money in PLN/EUR/USD/etc, but they still pay taxes in Poland, meaning they pay ZUS in PLN,
but I might implement it later.

**Comment by konradbartecki** [comment]
This is now deployed :) You can check it out by selecting currencies other than PLN, thanks a lot!
