### ISSUE TITLE
Use "brutto" instead of "netto"

### ISSUE THREAD

**Issue by hyzyla** [konradbartecki/Podatki.wtf.issues#34]
Seems like, there are typo and word "Brutto" should be used instead of "Netto", because right now  "Netto" on calculator is bigger than  "Do ręki co miesiąc"

![image](https://user-images.githubusercontent.com/7952949/203655319-b5f133d1-7ffe-44f2-ac46-24e6cf1f2dc2.png)

![A681CA8C-4CEB-417D-A959-CABCB16E5BF4_1_201_a](https://user-images.githubusercontent.com/7952949/203655100-9c46ae24-bb4b-4ef2-b9c2-6fe936d94b92.jpeg)

**Comment by konradbartecki** [comment]
It is correct in the B2B context, which is:
brutto = netto + VAT 23%
netto = without VAT
after tax = netto - PIT

VAT is not taken into consideration with this calculator, because it is mostly transparent, aka 100% of VAT you earned you will have to pay back anyway, unless you have some deductions.
