### ISSUE TITLE
Header link "Podatki.wtf" reffers to "https://www.polskilad.wtf/"

### ISSUE THREAD

**Issue by ZhenyaVasilevskiy** [konradbartecki/Podatki.wtf.issues#37]
![image](https://github.com/konradbartecki/Podatki.wtf.issues/assets/44446958/32fcf45a-0476-4d74-a1e4-81d62aabfc28)

**Comment by konradbartecki** [comment]
Thank you so much, I forgot about this one, I'll fix it soon.

**Comment by konradbartecki** [comment]
Fixed, thank you again!
