### ISSUE TITLE
250 płatnych dni urlopu powoduje zawieszenie się strony

### ISSUE THREAD

**Issue by BorkowskiDominik** [konradbartecki/Podatki.wtf.issues#39]
250 płatnych dni urlopu powoduje zawieszenie się strony. Prawdopodobnie wlatuje wtedy jakieś dzielenie przez 0.

P.S. Świetna stronka, chętnie korzystam, dzięki!

**Comment by konradbartecki** [comment]
Fixed by @MTheProgrammer, thanks! :)
