### ISSUE TITLE
English version

### ISSUE THREAD

**Issue by konradbartecki** [konradbartecki/Podatki.wtf.issues#5]

**Comment by jacekmusial** [comment]
@konradbartecki in case of English version, we should indicate that we are calculating taxes only from Poland, is that correct?

**Comment by konradbartecki** [comment]
Correct, however I don't think that I will deliver an English version anytime soon.
Thanks!
--
Kind Regards / Pozdrawiam
Konrad Bartecki

________________________________

**Comment by konradbartecki** [comment]
Won't do for now
