### ISSUE TITLE
Advanced option - 'Godzin pracy w tygodniu' - does not show results when manipulated.

### ISSUE THREAD

**Issue by borysrybak** [konradbartecki/Podatki.wtf.issues#6]
Advanced option - 'Godzin pracy w tygodniu' - does show results only when manipulated with certain values from specific range, i.e.: 20-24, 25-29, 30-34, etc.

example[1]:
providing 40 h/week has the same value as providing 44 h/week

It would be great if the app will handle more specified values for that particular option.
:) Pozdrawiam!

**Comment by konradbartecki** [comment]
Fixed! :-)
