### ISSUE TITLE
Adding "Ryczałt 15%" to "Stawka PIT" dropdown

### ISSUE THREAD

**Issue by emsipl** [konradbartecki/Podatki.wtf.issues#7]
Since "Ryczałt ewidencjonowany" is now available to programmers at lowered rate (15%) it has become an attractive alternative. Is it possible to add it to calculator?

**Comment by konradbartecki** [comment]
Wow thanks for letting me know, good news.
Yes I plan to release a new version along with new ZUS rates later this month.
I will look into that.

--
Kind Regards / Pozdrawiam
Konrad Bartecki

________________________________

**Comment by konradbartecki** [comment]
Released
