### ISSUE TITLE
Effective hourly and daily values

### ISSUE THREAD

**Issue by KamilMakowski** [konradbartecki/Podatki.wtf.issues#9]
Currently, for hourly and daily values we see net value (from invoice), it would be nice to see effective values meaning our hourly and daily, counts based on value "DO RĘKI CO MIESIĄC". Eg it can be added as small numbers in the brackets under main values

**Comment by konradbartecki** [comment]
In other words what you currently see is:
- "DO RĘKI CO MIESIĄC"
but you would also want to see:
- "do ręki co godzine" pln/h
- "do ręki co dzień" pln/d
am I right?

**Comment by KamilMakowski** [comment]
yes, exactly

**Comment by konradbartecki** [comment]
I want to keep the UI as clean as possible, so I added this feature under "Pokaż opcje zaawansowane".
It is now deployed and live on www.podatki.wtf, please check it out.

**Comment by KamilMakowski** [comment]
Great, thanks!

**Comment by KamilMakowski** [comment]
btw @konradbartecki should value in "Płatnych dni wolnych" have an impact on these new values which you just introduced?

**Comment by konradbartecki** [comment]
Short answer = no, because if you are using "Płatne dni wolne" then you are agreeing to work for a flat rate each month/year.
Therefore you will always get the same amount of money each month/year -> your real net/h or net/d doesn't change.

Now this calculator assumes everything in a time frame of a year, because leveled PIT like 17/32% is calculated for the whole year.

**Comment by konradbartecki** [comment]
Another thing to keep in mind is that this calculator can also freely switch between hourly/monthly/yearly rates.
Check out following - https://www.podatki.wtf/?n=10000,00&tax=3&d=202 
This is a calculation for earning 120k/year while working only 50 days per year.
If you will switch to PLN/h then you will see that you are getting 300 PLN/h.

300 PLN * 8 hours per day * 50 working days per year = 120k PLN / year
